name: image-ci

# When action should run
# on push to the stress branch
on:
  push:
    branches:
      - 'stress'

env:
  stress_image_name: 'pienczyk/stress'

jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout self to a runner
      - name: Checkout
        uses: actions/checkout@v4

      # Login to the Docker Hub. Secrets are configured in the GitHub/repository/settings/secrets/actions
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build, tag and push

      # stress
      # Build metadata for stress image
      - name: stress Docker metadata
        id: metastress
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.stress_image_name }}

          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}
